#!/usr/bin/env node
/**
 * Uploads a generated PDF for every seeded document row whose file is missing
 * from the "documents" bucket. LOCAL DEVELOPMENT ONLY — uses the service role key.
 *
 *   npm run db:seed:storage
 */
import { createClient } from '@supabase/supabase-js';

try {
  process.loadEnvFile('.env');
} catch {
  // Fall back to the real environment (CI).
}

const url = process.env.VITE_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!url || !serviceKey) {
  console.error('VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set (see .env.example).');
  process.exit(1);
}

if (!/^https?:\/\/(127\.0\.0\.1|localhost)/.test(url) && process.env.ALLOW_REMOTE_SEED !== 'true') {
  console.error(`Refusing to seed non-local Supabase at ${url}. Set ALLOW_REMOTE_SEED=true to override.`);
  process.exit(1);
}

const admin = createClient(url, serviceKey, { auth: { persistSession: false } });

/** Builds a small, valid single-page PDF containing the given lines of text. */
function buildPdf(lines) {
  const escape = (s) => s.replace(/[\\()]/g, (c) => `\\${c}`).replace(/[^\x20-\x7e]/g, '-');
  const text = lines
    .map((line, i) => `BT /F1 ${i === 0 ? 20 : 12} Tf 72 ${720 - i * 28} Td (${escape(line)}) Tj ET`)
    .join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${Buffer.byteLength(text)} >>\nstream\n${text}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [];
  objects.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.map((o) => `${String(o).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(pdf);
}

const { data: docs, error } = await admin
  .from('documents')
  .select('id, title, description, category, file_path, organization:organizations(name)');

if (error) {
  console.error('Could not read documents:', error.message);
  process.exit(1);
}

let uploaded = 0;
for (const doc of docs) {
  const pdf = buildPdf([
    doc.title,
    doc.organization?.name ?? '',
    `Category: ${doc.category}`,
    doc.description ?? '',
    'Sample document generated by the CommunityHub seed script.',
  ]);
  const { error: uploadError } = await admin.storage
    .from('documents')
    .upload(doc.file_path, pdf, { contentType: 'application/pdf', upsert: true });
  if (uploadError) {
    console.error(`  ✗ ${doc.file_path}: ${uploadError.message}`);
    continue;
  }
  uploaded += 1;
}

console.log(`Uploaded ${uploaded}/${docs.length} seed documents.`);
